version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: daily
- package-ecosystem: elm
  directory: "/example"
  schedule:
    interval: daily
- package-ecosystem: elm
  directory: "/test"
  schedule:
    interval: daily
