{
  "jobs":
    [
      {
        "template": "azure-pipelines-job.yml",
        "parameters": { "name": "Linux", "vmImage": "ubuntu-16.04" },
      },
      {
        "template": "azure-pipelines-job.yml",
        "parameters": { "name": "macOS", "vmImage": "macOS-10.13" },
      },
      {
        "template": "azure-pipelines-job.yml",
        "parameters": { "name": "Windows", "vmImage": "vs2017-win2016" },
      },
    ],
}
